#!/usr/bin/env php
<?php

require(__DIR__ . '/bootstrap.php');
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/environment.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

// minimal start up
if (in_array('--minimal', $argv)) {
    $config['bootstrap']['consoleBootstrap']['minimalBootstrap'] = true;
    $pluginManager = array_search('pluginManager', $config['bootstrap']);
    $themeManager = array_search('themeManager', $config['bootstrap']);
    $giiBootstrap = array_search('gii', $config['bootstrap']);

    unset($config['bootstrap'][$pluginManager]);
    unset($config['bootstrap'][$themeManager]);
    unset($config['bootstrap'][$giiBootstrap]);
    unset($config['modules']['gii']);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);